# Simple starship config

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$nodejs\
$rust\
$time\
$character"""

[directory]
style = "blue bold"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[❯](purple bold)"
error_symbol = "[❯](red bold)"
vimcmd_symbol = "[❮](green bold)"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bright-black bold"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan bold"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "*"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$symbol$version]($style) "
style = "bright-black bold"
symbol = " "

[nodejs]
format = "[$symbol$version]($style) "
style = "bright-black bold"
symbol = " "

[rust]
format = "[$symbol$version]($style) "
style = "bright-black bold"
symbol = " "

[time]
disabled = false
format = '[\[ $time \]]($style) '
style = "bright-black"
time_format = "%R" 