# Custom Starship configuration
# Here's a basic example - you can customize this further

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[directory]
truncation_length = 8
truncation_symbol = "…/"

[package]
disabled = false 