#!/bin/bash

##### Bar Appearance #####
sketchybar --bar position=top \
                height=34 \
                margin=10 \
                y_offset=5 \
                padding_left=10 \
                padding_right=10 \
                corner_radius=12 \
                color=0x00000000 \
                blur_radius=20 \
                --topmost=on \
                --sticky=off

##### Changing Defaults #####
default=(
  padding_left=4
  padding_right=4
  icon.font="FiraCode Nerd Font Mono:Bold:20.0"
  label.font="FiraCode Nerd Font Mono:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=8
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=8
  background.color=0x00000000
  background.border_width=2
  background.border_color=0xFF2962FF
  background.corner_radius=8
  background.height=32
  blur_radius=20
)

sketchybar --default "${default[@]}"

##### Adding Apple Logo #####
sketchybar --add item apple_logo left \
  --set apple_logo \
    icon="󰀵" \
    icon.font="FiraCode Nerd Font:Bold:20.0" \
    icon.color=0xffffffff \
    label.drawing=off \
    padding_left=15 \
    padding_right=15 \
    icon.padding_left=12 \
    icon.padding_right=12 \
    background.drawing=on \
    background.color=0x00000000 \
    background.border_width=2 \
    background.border_color=0xFF2962FF \
    background.corner_radius=8

##### Adding Workspaces Indicators #####
workspaces=$(/opt/homebrew/bin/aerospace list-workspaces --all)

for sid in $(echo $workspaces); do
  # Padding for visual alignment
  if [ "$sid" = "1" ]; then
    padding_left=5
  else
    padding_left=2
  fi
  padding_right=2

  sketchybar --add item space.$sid left \
             --set space.$sid \
                              icon="$sid"                   \
                              icon.font="FiraCode Nerd Font:Bold:16.0"   \
                              icon.color=0xFFFFFFFF                      \
                              label.drawing=on                          \
                              label.font="FiraCode Nerd Font:Bold:16.0" \
                              label.color=0xFF992B3F5                    \
                              padding_left=$padding_left                  \
                              padding_right=$padding_right               \
                              background.drawing=on                      \
                              background.color=0x00000000               \
                              background.border_width=0                  \
                              background.height=32                      \
                              background.corner_radius=8               \
                              click_script="aerospace workspace $sid"    \
                              script="$HOME/.config/sketchybar/plugins/workspace_changed.sh" \
             --subscribe space.$sid aerospace_workspace_change front_app_switched window_focus
done

sketchybar --add bracket spaces '/space\..*/' \
           --set spaces background.border_width=0

##### Adding Front App Display #####
sketchybar --add item front_app.app e \
  --set front_app.app \
    icon.font="sketchybar-app-font:Normal:22.0" \
    icon.color=0xFFFFB74D \
    label.color=0xFFFFFFFF \
    padding_right=0 \
    label.max_chars=16 \
    scroll_texts=on \
    background.drawing=off \
    script="$HOME/.config/sketchybar/plugins/front_app.sh" \
  --subscribe front_app.app front_app_switched

sketchybar --add item front_app.title e \
  --set front_app.title \
    label.font="FiraCode Nerd Font:Bold:12.0" \
    label.color=0xFF992B3F5 \
    label.max_chars=26 \
    padding_left=0 \
    scroll_texts=on \
    icon.drawing=off \
    background.drawing=off \
    label="Title" \
    script="$HOME/.config/sketchybar/plugins/front_app_title.sh" \
  --subscribe front_app.title front_app_switched

sketchybar --add bracket front_app '/front_app.*/'

##### Adding Clock, Volume, and Battery #####
sketchybar --add item clock right \
  --set clock update_freq=10 icon=  script="$HOME/.config/sketchybar/plugins/clock.sh" \
    icon.font="FiraCode Nerd Font:Bold:18.0" \
    label.font="FiraCode Nerd Font:Bold:14.0" \
    label.color=0xFF992B3F5 \
    padding_right=5 \
    background.drawing=on \
    background.color=0x00000000 \
    background.border_width=2 \
    background.border_color=0xFF2962FF \
    background.corner_radius=8 \
  --add item volume right \
  --set volume script="$HOME/.config/sketchybar/plugins/volume.sh" \
    icon.font="FiraCode Nerd Font:Bold:18.0" \
    label.font="FiraCode Nerd Font:Bold:14.0" \
    label.color=0xFF992B3F5 \
    padding_right=5 \
    background.drawing=on \
    background.color=0x00000000 \
    background.border_width=2 \
    background.border_color=0xFF2962FF \
    background.corner_radius=8 \
  --subscribe volume volume_change \
  --add item battery right \
  --set battery script="$HOME/.config/sketchybar/plugins/battery.sh" \
    icon.font="FiraCode Nerd Font:Bold:18.0" \
    label.font="FiraCode Nerd Font:Bold:14.0" \
    label.color=0xFF992B3F5 \
    update_freq=120 \
    padding_right=5 \
    background.drawing=on \
    background.color=0x00000000 \
    background.border_width=2 \
    background.border_color=0xFF2962FF \
    background.corner_radius=8 \
  --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time #####
sketchybar --update

# Initialize workspace display
$HOME/.config/sketchybar/plugins/workspace_changed.sh