# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/i3ahp5sj65dixlala8py18qrvmp76gil-hm-session-vars.fish



status is-login; and begin

    # Login shell initialisation


end

status is-interactive; and begin

    # Abbreviations
    abbr --add -- ff fastfetch
    abbr --add -- nb '/run/current-system/sw/bin/darwin-rebuild build --flake .#aarch64-darwin'
    abbr --add -- nbs '/run/current-system/sw/bin/darwin-rebuild switch --flake .#aarch64-darwin'

    # Aliases
    alias cat bat
    alias cd z
    alias diff difft
    alias la 'eza -la --icons=always'
    alias ll 'eza -l --icons=always'
    alias ls 'eza --icons=always'
    alias pn pnpm
    alias px pnpx
    alias search 'rg -p --glob '\''!node_modules/*'\'''
    alias tree 'eza --tree --icons=always'

    # Interactive shell initialisation
    # Set environment variables
    set -x PATH $HOME/.pnpm-packages/bin $HOME/.pnpm-packages $PATH
    set -x PATH $HOME/.npm-packages/bin $HOME/bin $PATH
    set -x PATH $HOME/.local/share/bin $PATH

    # Remove history data we don't want to see
    set -x HISTIGNORE "pwd:ls:cd"

    # Initialize zoxide (better cd)
    zoxide init fish | source

    # Run fastfetch if we're in kitty
    if test "$TERM" = xterm-kitty
        fastfetch
    end

    if set -q KITTY_INSTALLATION_DIR
        set --global KITTY_SHELL_INTEGRATION no-rc
        source "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish"
        set --prepend fish_complete_path "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_completions.d"
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/Users/mike/.local/share/fish/home-manager_generated_completions" $post
    end


end
